from train.train_action_repeat import train_2
from train.train_single_button import train_5

def main():
    train_2(MAX_TIMESTEPS = int(2e6),
            START_TIMESTEPS = int(2e5),
            LOAD_MODEL = None,
            LOAD_RESULTS_PATH = None,
            ENV_NAME = "SafetyRacecarButton2-v0",
            MAX_STEPS = 1000,
            BATCH_SIZE = 256,
            EVAL_FREQ = 25000,
            SAC_EVAL_EPISODES = 30,
            GAMMA = 0.99,
            TAU = 0.005,
            ACTOR_LR = 1e-4,
            CRITIC_LR = 1e-4,
            entropy_multiplier = 1.0,
            COST_WEIGHT = 0.000,
            TURNING_WEIGHT = 0.0,
            SEED = 0,
            SAC_MODEL_PATH = "models/",
            AGENT_ID = "sac_baseline",
            )
    
    train_2(MAX_TIMESTEPS = int(1e6),
            START_TIMESTEPS = int(5e4),
            LOAD_MODEL = None,
            LOAD_RESULTS_PATH = None,
            ENV_NAME = "SafetyRacecarButton2-v0",
            MAX_STEPS = 500,
            BATCH_SIZE = 256,
            REPLAY_BUFFER_SIZE = int(3e5),
            EVAL_FREQ = 25000,
            SAC_EVAL_EPISODES = 30,
            GAMMA = 0.99,
            TAU = 0.005,
            ACTOR_LR = 5e-5,
            CRITIC_LR = 5e-5,
            entropy_multiplier = 1.0,
            COST_WEIGHT = 0.0,
            TURNING_WEIGHT = 0,
            ACTION_REPEAT = 2,
            SEED = 0,
            SAC_MODEL_PATH = "models/",
            AGENT_ID = "sac_ms_500_ar2_c0_em1_mt1e6_st_5e4",
            )
    

    train_2(MAX_TIMESTEPS = int(1e6),
            START_TIMESTEPS = int(5e4),
            LOAD_MODEL = "sac_ms_500_ar2_c0_em1_mt1e6_st_5e4_best",
            LOAD_RESULTS_PATH = None,
            ENV_NAME = "SafetyRacecarButton2-v0",
            MAX_STEPS = 500,
            BATCH_SIZE = 256,
            REPLAY_BUFFER_SIZE = int(3e5),
            EVAL_FREQ = 25000,
            SAC_EVAL_EPISODES = 30,
            GAMMA = 0.99,
            TAU = 0.005,
            ACTOR_LR = 5e-5,
            CRITIC_LR = 5e-5,
            entropy_multiplier = 1.0,
            COST_WEIGHT = 0.005,
            TURNING_WEIGHT = 0,
            ACTION_REPEAT = 2,
            SEED = 0,
            SAC_MODEL_PATH = "models/",
            AGENT_ID = "sac_ms_500_ar2_c0toc005_em1_mt1e6_st_5e4",
            )



    train_5(MAX_TIMESTEPS = int(7e5),
            START_TIMESTEPS = int(5e4),
            LOAD_MODEL = None,
            LOAD_RESULTS_PATH = None,
            ENV_NAME = "SafetyRacecarButton2-v0",
            MAX_STEPS = 500,
            BATCH_SIZE = 256,
            REPLAY_BUFFER_SIZE = int(3e5),
            EVAL_FREQ = 10000,
            SAC_EVAL_EPISODES = 30,
            GAMMA = 0.99,
            TAU = 0.005,
            ACTOR_LR = 5e-5,
            CRITIC_LR = 5e-5,
            entropy_multiplier = 1.0,
            COST_WEIGHT = 0.0,
            TURNING_WEIGHT = 0,
            ACTION_REPEAT = 2,
            SEED = 0,
            SAC_MODEL_PATH = "models/",
            AGENT_ID = "sac_single_B_ar2_c0_em1_rbs3e5_st5e4_mt1e6",
            )
   
    train_5(MAX_TIMESTEPS = int(7e5),
            START_TIMESTEPS = int(5e4),
            LOAD_MODEL = "sac_single_B_ar2_c0_em1_rbs3e5_st5e4_mt1e6_best",
            LOAD_RESULTS_PATH = None,
            ENV_NAME = "SafetyRacecarButton2-v0",
            MAX_STEPS = 500,
            BATCH_SIZE = 256,
            REPLAY_BUFFER_SIZE = int(3e5),
            EVAL_FREQ = 10000,
            SAC_EVAL_EPISODES = 30,
            GAMMA = 0.99,
            TAU = 0.005,
            ACTOR_LR = 5e-5,
            CRITIC_LR = 5e-5,
            entropy_multiplier = 1.0,
            COST_WEIGHT = 0.05,
            TURNING_WEIGHT = 0,
            ACTION_REPEAT = 2,
            SEED = 0,
            SAC_MODEL_PATH = "models/",
            AGENT_ID = "sac_single_B_ar2_c0toc05_em1_rbs3e5_st5e4_mt1e6", 
            )
    

    train_5(MAX_TIMESTEPS = int(1e6),
            START_TIMESTEPS = int(5e4),
            LOAD_MODEL = "sac_single_B_ar2_c0toc05_em1_rbs3e5_st5e4_mt1e6_best",
            LOAD_RESULTS_PATH = None,
            ENV_NAME = "SafetyRacecarButton2-v0",
            MAX_STEPS = 500,
            BATCH_SIZE = 256,
            REPLAY_BUFFER_SIZE = int(3e5),
            EVAL_FREQ = 10000,
            SAC_EVAL_EPISODES = 30,
            GAMMA = 0.99,
            TAU = 0.005,
            ACTOR_LR = 5e-5,
            CRITIC_LR = 5e-5,
            entropy_multiplier = 1.0,
            COST_WEIGHT = 0.1,
            TURNING_WEIGHT = 0,
            ACTION_REPEAT = 2,
            SEED = 0,
            SAC_MODEL_PATH = "models/",
            AGENT_ID = "sac_single_B_ar2_c05toc1_em1_rbs3e5_st5e4_mt1e6",
            )

if __name__ == "__main__":
    main()