from train.train_action_repeat import train_2
from train.train_entropy_scheduler import train_4

def main():

    # neo peirama: meiosi megethos epeisodiou se 500 me action repeat 2
    # *afou teleiose* to kalutero mexri tora avg reward exi ftasei to 16 se peak gia mikos ep 1000

    #  train_2(MAX_TIMESTEPS = int(1e6),
    #         START_TIMESTEPS = int(5e4),
    #         LOAD_MODEL = None,
    #         LOAD_RESULTS_PATH = None,
    #         ENV_NAME = "SafetyRacecarButton2-v0",
    #         MAX_STEPS = 500,
    #         BATCH_SIZE = 256,
    #         REPLAY_BUFFER_SIZE = int(3e5),
    #         EVAL_FREQ = 25000,
    #         SAC_EVAL_EPISODES = 30,
    #         GAMMA = 0.99,
    #         TAU = 0.005,
    #         ACTOR_LR = 5e-5,
    #         CRITIC_LR = 5e-5,
    #         entropy_multiplier = 1.0,
    #         COST_WEIGHT = 0.0,
    #         TURNING_WEIGHT = 0,
    #         ACTION_REPEAT = 2,
    #         SEED = 0,
    #         SAC_MODEL_PATH = "models/",
    #         AGENT_ID = "sac_ms_500_ar2_c0_em1_mt1e6_st_5e4",
    #         )
     #phase2 tou pano "sac_ms_500_ar2_c0_em1_mt1e6_st_5e4"
    train_2(MAX_TIMESTEPS = int(1e6),
            START_TIMESTEPS = int(5e4),
            LOAD_MODEL = "sac_ms_500_ar2_c0_em1_mt1e6_st_5e4_best",
            LOAD_RESULTS_PATH = None,
            ENV_NAME = "SafetyRacecarButton2-v0",
            MAX_STEPS = 500,
            BATCH_SIZE = 256,
            REPLAY_BUFFER_SIZE = int(3e5),
            EVAL_FREQ = 25000,
            SAC_EVAL_EPISODES = 30,
            GAMMA = 0.99,
            TAU = 0.005,
            ACTOR_LR = 5e-5,
            CRITIC_LR = 5e-5,
            entropy_multiplier = 1.0,
            COST_WEIGHT = 0.005,
            TURNING_WEIGHT = 0,
            ACTION_REPEAT = 2,
            SEED = 0,
            SAC_MODEL_PATH = "models/",
            AGENT_ID = "sac_ms_500_ar2_c0toc005_em1_mt1e6_st_5e4",
            )
    

    # ayto einai apisteyta smooth , den kseo an einai ta parameters h to lathos train file pou eix aftiaksei
    # train_2(MAX_TIMESTEPS = int(1e6),
    #         START_TIMESTEPS = int(1e5),
    #         LOAD_MODEL = None,
    #         LOAD_RESULTS_PATH = None,
    #         ENV_NAME = "SafetyRacecarButton2-v0",
    #         MAX_STEPS = 1000,
    #         BATCH_SIZE = 256,
    #         EVAL_FREQ = 25000,
    #         SAC_EVAL_EPISODES = 30,
    #         GAMMA = 0.99,
    #         TAU = 0.005,
    #         ACTOR_LR = 1e-4,
    #         CRITIC_LR = 1e-4,
    #         entropy_multiplier = 1.0,
    #         COST_WEIGHT = 0.0,
    #         TURNING_WEIGHT = 0,
    #         ACTION_REPEAT = 2,
    #         SEED = 0,
    #         SAC_MODEL_PATH = "models/",
    #         AGENT_ID = "sac_c0_act_r_2",
    #         )


    # train_2(MAX_TIMESTEPS = int(1e6),
    #         START_TIMESTEPS = int(1e5),
    #         LOAD_MODEL = None,
    #         LOAD_RESULTS_PATH = None,
    #         ENV_NAME = "SafetyRacecarButton2-v0",
    #         MAX_STEPS = 1000,
    #         BATCH_SIZE = 256,
    #         EVAL_FREQ = 25000,
    #         SAC_EVAL_EPISODES = 30,
    #         GAMMA = 0.99,
    #         TAU = 0.005,
    #         ACTOR_LR = 1e-4,
    #         CRITIC_LR = 1e-4,
    #         entropy_multiplier = 1.0,
    #         COST_WEIGHT = 0.0,
    #         TURNING_WEIGHT = 0,
    #         ACTION_REPEAT = 2,
    #         SEED = 0,
    #         SAC_MODEL_PATH = "models/",
    #         AGENT_ID = "sac_c0_act_r_2_v2",
    #         )
    

    # this one is good , can be used as baseline, avg reward around 11, cost still high
    # train_2(MAX_TIMESTEPS = int(2e6),
    #         START_TIMESTEPS = 0,
    #         LOAD_MODEL = "sac_ms2000_ar2_c0_best",
    #         LOAD_RESULTS_PATH = "",
    #         ENV_NAME = "SafetyRacecarButton2-v0",
    #         MAX_STEPS = 1000,
    #         BATCH_SIZE = 256,
    #         EVAL_FREQ = 25000,
    #         SAC_EVAL_EPISODES = 30,
    #         GAMMA = 0.99,
    #         TAU = 0.005,
    #         ACTOR_LR = 1e-4,
    #         CRITIC_LR = 1e-4,
    #         entropy_multiplier = 1.0,
    #         COST_WEIGHT = 0.005,
    #         TURNING_WEIGHT = 0,
    #         ACTION_REPEAT = 2,
    #         SEED = 0,
    #         SAC_MODEL_PATH = "models/",
    #         AGENT_ID = "sac_ms2000_ar2_c0_phase_2_c005",
    #         )
    


    # train_2(MAX_TIMESTEPS = int(2e6),
    #         START_TIMESTEPS = 0,
    #         LOAD_MODEL = "sac_ms2000_ar2_c0_phase_2_c005_best",
    #         LOAD_RESULTS_PATH = "",
    #         ENV_NAME = "SafetyRacecarButton2-v0",
    #         MAX_STEPS = 1000,
    #         BATCH_SIZE = 256,
    #         EVAL_FREQ = 25000,
    #         SAC_EVAL_EPISODES = 30,
    #         GAMMA = 0.99,
    #         TAU = 0.005,
    #         ACTOR_LR = 5e-5,
    #         CRITIC_LR = 5e-5,
    #         entropy_multiplier = 1.0,
    #         COST_WEIGHT = 0.01,
    #         TURNING_WEIGHT = 0,
    #         ACTION_REPEAT = 2,
    #         SEED = 0,
    #         SAC_MODEL_PATH = "models/",
    #         AGENT_ID = "sac_ms2000_ar2_c005_phase_3_c01",
    #         )

    #sunexisi tou apo pano me idio cost 0.01 alla auksisi entropy giati kollaei kai leipei explore
    # train_2(MAX_TIMESTEPS = int(2e6),
    #         START_TIMESTEPS = 0,
    #         LOAD_MODEL = "sac_ms2000_ar2_c005_phase_3_c01_best",
    #         LOAD_RESULTS_PATH = "",
    #         ENV_NAME = "SafetyRacecarButton2-v0",
    #         MAX_STEPS = 1000,
    #         BATCH_SIZE = 256,
    #         EVAL_FREQ = 25000,
    #         SAC_EVAL_EPISODES = 30,
    #         GAMMA = 0.99,
    #         TAU = 0.005,
    #         ACTOR_LR = 5e-5,
    #         CRITIC_LR = 5e-5,
    #         entropy_multiplier = 1.25,
    #         COST_WEIGHT = 0.01,
    #         TURNING_WEIGHT = 0,
    #         ACTION_REPEAT = 2,
    #         SEED = 0,
    #         SAC_MODEL_PATH = "models/",
    #         AGENT_ID = "sac_ms2000_ar2_c005_phase_4_c01_em15e1",
    #         )
    
    # den vriseki troxi apofugis. ulopoiisi me entrpy scheculer

    # train_4(MAX_TIMESTEPS = int(2e6),
    #         START_TIMESTEPS = 0,
    #         LOAD_MODEL = "sac_ms2000_ar2_c0_phase_2_c005_best",
    #         LOAD_RESULTS_PATH = "",
    #         ENV_NAME = "SafetyRacecarButton2-v0",
    #         MAX_STEPS = 1000,
    #         BATCH_SIZE = 256,
    #         EVAL_FREQ = 25000,
    #         SAC_EVAL_EPISODES = 30,
    #         GAMMA = 0.99,
    #         TAU = 0.005,
    #         ACTOR_LR = 5e-5,
    #         CRITIC_LR = 5e-5,
    #         entropy_multiplier = 1.0,
    #         COST_WEIGHT = 0.01,
    #         TURNING_WEIGHT = 0,
    #         ACTION_REPEAT = 2,
    #         SEED = 0,
    #         SAC_MODEL_PATH = "models/",
    #         AGENT_ID = "sac_ms2000_ar2_c005_to_c01_em_3to1_25",
    #         )
    
    # efage crash to apo pano sta 300k iter fml
    #sunexisi tou -->
    

    # train_4(MAX_TIMESTEPS = int(2e6),
    #         START_TIMESTEPS = 0,
    #         LOAD_MODEL = "sac_ms2000_ar2_c005_to_c01_em_3to1_25_latest",
    #         LOAD_RESULTS_PATH = "",
    #         ENV_NAME = "SafetyRacecarButton2-v0",
    #         MAX_STEPS = 1000,
    #         BATCH_SIZE = 256,
    #         EVAL_FREQ = 25000,
    #         SAC_EVAL_EPISODES = 30,
    #         GAMMA = 0.99,
    #         TAU = 0.005,
    #         ACTOR_LR = 5e-5,
    #         CRITIC_LR = 5e-5,
    #         entropy_multiplier = 1.0,
    #         COST_WEIGHT = 0.01,
    #         TURNING_WEIGHT = 0,
    #         ACTION_REPEAT = 2,
    #         SEED = 0,
    #         SAC_MODEL_PATH = "models/",
    #         AGENT_ID = "sac_ms2000_ar2_c005_to_c01_em_3to1_25_continue",
    #         )

    #enallaktiko tou "sac_ar2_to_ar1_c01_em_2to1_25_rb_3e5_st5e4"
    # train_4(MAX_TIMESTEPS = int(2e6),
    #         START_TIMESTEPS = int(5e4),
    #         LOAD_MODEL = "sac_ar2_c005_to_c01_em_3to1_25_rb_3e5_st5e4_best",
    #         LOAD_RESULTS_PATH = "",
    #         ENV_NAME = "SafetyRacecarButton2-v0",
    #         MAX_STEPS = 1000,
    #         BATCH_SIZE = 256,
    #         REPLAY_BUFFER_SIZE = int(3e5),
    #         EVAL_FREQ = 25000,
    #         SAC_EVAL_EPISODES = 30,
    #         GAMMA = 0.99,
    #         TAU = 0.005,
    #         ACTOR_LR = 5e-5,
    #         CRITIC_LR = 5e-5,
    #         entropy_multiplier = 1.0,
    #         COST_WEIGHT = 0.01,
    #         TURNING_WEIGHT = 0,
    #         ACTION_REPEAT = 2,
    #         SEED = 0,
    #         SAC_MODEL_PATH = "models/",
    #         AGENT_ID = "sac_ar2_c01_em_2to1_25_rb_3e5_st5e4_repeat1",
    #         )
    


    # train_2(MAX_TIMESTEPS = int(1e6),
    #         START_TIMESTEPS = int(3e5),
    #         LOAD_MODEL = None,
    #         LOAD_RESULTS_PATH = None,
    #         ENV_NAME = "SafetyRacecarButton2-v0",
    #         MAX_STEPS = 1000,
    #         BATCH_SIZE = 256,
    #         EVAL_FREQ = 25000,
    #         SAC_EVAL_EPISODES = 30,
    #         GAMMA = 0.99,
    #         TAU = 0.005,
    #         ACTOR_LR = 1e-4,
    #         CRITIC_LR = 1e-4,
    #         entropy_multiplier = 1.0,
    #         COST_WEIGHT = 0.005,
    #         TURNING_WEIGHT = 0,
    #         ACTION_REPEAT = 2,
    #         SEED = 0,
    #         SAC_MODEL_PATH = "models/",
    #         AGENT_ID = "sac_c005_act_r_2_v2",
    #         )


    # train_2(MAX_TIMESTEPS = int(1e6),
    #         START_TIMESTEPS = int(1e5),
    #         LOAD_MODEL = None,
    #         LOAD_RESULTS_PATH = None,
    #         ENV_NAME = "SafetyRacecarButton2-v0",
    #         MAX_STEPS = 1000,
    #         BATCH_SIZE = 256,
    #         EVAL_FREQ = 25000,
    #         SAC_EVAL_EPISODES = 30,
    #         GAMMA = 0.99,
    #         TAU = 0.005,
    #         ACTOR_LR = 1e-4,
    #         CRITIC_LR = 1e-4,
    #         entropy_multiplier = 2.0,
    #         COST_WEIGHT = 0.01,
    #         TURNING_WEIGHT = 0.01,
    #         ACTION_REPEAT = 2,
    #         SEED = 0,
    #         SAC_MODEL_PATH = "models/",
    #         AGENT_ID = "sac_clone_wars_c01_tw_01_ar_2",
    #         )



if __name__ == "__main__":
    main()